PRODUCER_WELL_RJS_739 = {
    'FPSO-PL_20_FIT_0155_CVOL': 'Well liquid rate, standard conditions',
    'FPSO-PL_20_FIT_0155_UVOL': 'Well liquid rate, in-situ conditions',
    'FPSO-PL_13_PZT_5004': 'Pressure downstream of choke',
    'FPSO-PL_13_TZT_5066': 'Temperature downstream of choke',
    'FPSO-PL_13_MOV_5070': 'Choke Position',
    'FPSO-PL_13_PIT_5003': 'Pressure upstream of choke',
    'FPSO-PL_13_TIT_5043': 'Temperature upstream of choke',
    'Poco_RJS_739_SCM_1_MA_36': 'Wellhead Pressure',
    'Poco_RJS_739_SCM_1_MA_37': 'Wellhead Temperature',
    'Poco_RJS_739_SCM_1_IWIS_MA4_P': 'Tubing Dowhnole pressure',
    'Poco_RJS_739_SCM_1_IWIS_MA4_T': 'Tubing Downhole temperature',
    'Poco_RJS_739_SCM_1_IWIS_MA3_P': 'Top ICV annular pressure',
    'Poco_RJS_739_SCM_1_IWIS_MA3_T': 'Top ICV annular temperature',
    'Poco_RJS_739_SCM_1_IWIS_MA2_P': 'Bottom ICV annular pressure',
    'Poco_RJS_739_SCM_1_IWIS_MA2_T': 'Bottom ICV annular temperature',
    'RJS_739_ESTADO_POCO': 'Well Status flag (flowing/no flowing)',
    'FPSO-PL_20_FIT_0255_CVOL': 'Well liquid rate, standard conditions (backup)',
    'FPSO-PL_20_FIT_0255_UVOL': 'Well liquid rate, in-situ conditions (backup)',
    'FPSO-PL_13_MOV_5070_SP': 'Choke Position (backup)',
    'FPSO-PL_13_PZT_5002': 'Pressure upstream of choke (backup)',
    'Poco_RJS_739_SCM_1_IWIS_MA5_P': 'Tubing Dowhnole pressure (backup)',
    'Poco_RJS_739_SCM_1_IWIS_MA5_T': 'Tubing Downhole temperature (backup)',
    'Poco_RJS_739_SCM_1_IWIS_MA6_P': 'Top ICV annular pressure (backup)',
    'Poco_RJS_739_SCM_1_IWIS_MA6_T': 'Top ICV annular temperature (backup)',
    'Poco_RJS_739_SCM_1_IWIS_MA7_P': 'Bottom ICV annular pressure (backup)',
    'Poco_RJS_739_SCM_1_IWIS_MA7_T': 'Bottom ICV annular temperature (backup)'
}

INJECTOR_WELL_RJS_742 = {
    'FPSO-PL_26_FIT_1195_CVOL': 'Well liquid rate, standard conditions',
    'FPSO-PL_26_FIT_1064': 'Well liquid rate, in-situ conditions',
    'FPSO-PL_13_PZT_5012': 'Pressure downstream of choke',
    'FPSO-PL_13_TZT_5068': 'Temperature downstream of choke',
    'FPSO-PL_13_MOV_5071': 'Choke Position',
    'FPSO-PL_13_PIT_5011': 'Pressure upstream of choke',
    'FPSO-PL_13_TIT_5045': 'Temperature upstream of choke',
    'Poco_RJS_742_SCM_3_MA_35': 'Wellhead Pressure',
    'Poco_RJS_742_SCM_3_MA_36': 'Wellhead Temperature',
    'Poco_RJS_742_SCM_3_IWIS_MA4_P': 'Tubing Dowhnole pressure',
    'Poco_RJS_742_SCM_3_IWIS_MA4_T': 'Tubing Downhole temperature',
    'Poco_RJS_742_SCM_3_IWIS_MA3_P': 'Top ICV annular pressure',
    'Poco_RJS_742_SCM_3_IWIS_MA3_T': 'Top ICV annular temperature',
    'Poco_RJS_742_SCM_3_IWIS_MA2_P': 'Middle ICV annular pressure',
    'Poco_RJS_742_SCM_3_IWIS_MA2_T': 'Middle ICV annular temperature',
    'Poco_RJS_742_SCM_3_IWIS_MA1_P': 'Bottom ICV annular pressure',
    'Poco_RJS_742_SCM_3_IWIS_MA1_T': 'Bottom ICV annular temperature',
    'RJS_742_ESTADO_POCO': 'Well Status flag (flowing/no flowing)',
    'FPSO-PL_26_FIT_1295_CVOL': 'Well liquid rate, standard conditions (backup)',
    'FPSO-PL_13_PZT_5010': 'Pressure upstream of choke (backup)',
    'Poco_RJS_742_SCM_3_IWIS_MA5_P': 'Tubing Dowhnole pressure (backup)',
    'Poco_RJS_742_SCM_3_IWIS_MA5_T': 'Tubing Downhole temperature (backup)',
    'Poco_RJS_742_SCM_3_IWIS_MA6_P': 'Top ICV annular pressure (backup)',
    'Poco_RJS_742_SCM_3_IWIS_MA6_T': 'Top ICV annular temperature (backup)',
    'Poco_RJS_742_SCM_3_IWIS_MA7_P': 'Middle ICV annular pressure (backup)',
    'Poco_RJS_742_SCM_3_IWIS_MA7_T': 'Middle ICV annular temperature (backup)',
    'Poco_RJS_742_SCM_3_IWIS_MA8_P': 'Bottom ICV annular pressure (backup)',
    'Poco_RJS_742_SCM_3_IWIS_MA8_T': 'Bottom ICV annular temperature (backup)'
}